name: ci

on:
  pull_request:
    paths-ignore:
    - CONTRIBUTING.md
    - README.md
  push:
    branches:
    - main
    paths-ignore:
    - CONTRIBUTING.md
    - README.md
  workflow_call:
    inputs:
      release:
        description: Whether this is running as part of a release workflow.
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          goos: windows
        - os: ubuntu-latest
          goos: linux
        - os: macos-latest
          goos: darwin
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Test
      run: GOOS=${{ matrix.goos }} go test ./... -cover -coverprofile=coverage.txt -race -v
    - name: Report coverage
      uses: codecov/codecov-action@v5

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Lint
      # cspell:ignore golangci
      uses: golangci/golangci-lint-action@v8
      with:
        only-new-issues: true
    - name: Check spelling
      if: ${{ !cancelled() }}
      uses: streetsidesoftware/cspell-action@v6
      with:
        config: .vscode/cspell.json

  check:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
    - lint
    - test
    steps:
    - name: Fail
      if: needs.lint.result != 'success' || needs.test.result != 'success'
      run: exit 1
